### ISSUE TITLE
Freezes Sketch

### ISSUE THREAD

**Issue by captainill** [ryanjohnson-me/Sketch-Copy-Paste-Shadows#2]
maybe something has changed in Sketch since the plugin creation. Managed to find this repo via google. Definitely functionality I'd like but the pasting locks up Sketch. Any idea why?

**Comment by captainill** [comment]
Keep finding this plugin. It doesn't freeze sketch anymore it just doesn't do anything. I'm sure a lot has changed in Sketch.

**Comment by ryanjohnson-me** [comment]
Sorry for late reply. I have fixed it and now works for 3.8+
