### ISSUE TITLE
Stoped working after Sketch update...

### ISSUE THREAD

**Issue by ozcarstorm** [ryanjohnson-me/Sketch-Copy-Paste-Shadows#3]
Hi! 

Thank you for this plugin, very useful!!

Unfortunately, after updating to latest version of Sketch, it stopped working. Nothing happens when I copy & paste shadows from the plugin anymore... 

Sketch Version 39.1 (31720)

**Comment by rodnem** [comment]
same here

**Comment by ryanjohnson-me** [comment]
@ozcarstormer  @rodnem Updated (Tested on Sketch 42)
