### ISSUE TITLE
Not working in Sketch 4.1

### ISSUE THREAD

**Issue by danaanclarke** [ryanjohnson-me/Sketch-Copy-Paste-Shadows#4]
Installed the plugin fine, but copy and pasting doesn't seem to work in Sketch 4.1, would love to see an update!

**Comment by rodnem** [comment]
+1 Please update it :)
Your plug is great, we need it ...

**Comment by ryanjohnson-me** [comment]
@danaanclarke @rodnem Updated (Tested on Sketch 42)
